### ISSUE TITLE
Tried to use it but...

### ISSUE THREAD

**Issue by Vlandmist** [Core-Techs/Winscp.Extensions#2]
it gave me problems on vs2013 on `session.Open("string")`
something related to specific assembly version not found. had to uninstall it

**Comment by Vlandmist** [comment]
care to write a comment about my issue?

**Comment by ronnieoverby** [comment]
I'd be glad to help, but you didn't include very much context around your issue.

"it gave me problems" is not enough.

It's best to send a stack trace and failing code. A complete project that demonstrates the problem (AND ONLY THE PROBLEM) is best.

Many times you'll fix the issue yourself when you isolate it.
